apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of Esentutl, a built-in command-line program that can be used to copy NTDS.dit and dump Active Directory credentials - ATT&CK T1003.003
  discard_data: false
  interval: 600
  name: MITRE - Database Utility
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%esentutl%';
