apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of InstallUtil, a command-line utility that allows installation and uninstallation of resources by executing installer components in .NET binaries - ATT&CK T1218.004
  discard_data: false
  interval: 600
  name: MITRE - InstallUtil Execution
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%InstallUtil%';
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of CMSTP.exe, the Microsoft Connection Manager Profile Installer used to install Connection Manager service profiles - ATT&CK T1218.003
  discard_data: false
  interval: 600
  name: MITRE - Connection Manager Profile
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%CMSTP%';
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of Mshta, a utility that executes Microsoft HTML Applications (HTA) - ATT&CK T1218.005
  discard_data: false
  interval: 600
  name: MITRE - HTML Application
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%mshta%';
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of Certutil.exe, a built-in command-line program to manage certificates that can be misused for malicious purposes - ATT&CK T1218.003
  discard_data: false
  interval: 600
  name: MITRE - Certificate Utility
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%certutil%';
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Monitor usage of PowerShell, a powerful interactive command-line interface and scripting environment that can be misused - ATT&CK T1218.011
  discard_data: false
  interval: 600
  name: MITRE - DLL Registration
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%regsvr%';
