# MITRE ATT&CK Technique: linux_local_job_scheduling
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/linux_local_job_scheduling.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: List Local job scheduling with Cron - ATT&CK T1168
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: local_job_scheduling
  observer_can_run: false
  platform: ""
  query: select command, path from crontab;
  team: ""
