# MITRE ATT&CK Technique: linux_relevant_folder_check
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/linux_relevant_folder_check.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIR1 dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: YOURIMPDIR1_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIR1/%/%') OR
    (fi.path like '/YOURIMPDIR1/%%/.%') OR (fi.path like '/YOURIMPDIR1/.%') OR (fi.path
    like '/YOURIMPDIR1/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIR2 dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: YOURIMPDIR2_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIR2/%/%') OR
    (fi.path like '/YOURIMPDIR2/%%/.%') OR (fi.path like '/YOURIMPDIR2/.%') OR (fi.path
    like '/YOURIMPDIR2/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIRn dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: YOURIMPDIRn_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIRn/%/%') OR
    (fi.path like '/YOURIMPDIRn/%%/.%') OR (fi.path like '/YOURIMPDIRn/.%') OR (fi.path
    like '/YOURIMPDIRn/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under all home user dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: home_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%/%') OR (fi.path
    like '/home/%') OR (fi.path like '/home/%/.%')OR (fi.path like '/home/.%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under root dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: root_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/root/%/%') OR (fi.path
    like '/root/%') OR (fi.path like '/root/%/.%')OR (fi.path like '/root/.%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under tmp dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: tmp_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/tmp/%/%') OR (fi.path
    like '/tmp/.%')OR (fi.path like '/tmp/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under www dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: var_www_dir_check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/var/www/%/%') OR (fi.path
    like '/var/www/%/.%')OR (fi.path like '/var/www/.%') OR (fi.path like '/var/www/.%'));
  team: ""
