# MITRE ATT&CK Technique: linux_users_check
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/linux_users_check.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists last logged in users - ATT&CK T1136,T1078
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: linux_last_logged_users
  observer_can_run: false
  platform: ""
  query: select datetime(time,'unixepoch','UTC') as time_utc,host,username,tty,pid,type
    from last;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all logged in users - ATT&CK T1136,T1078,T1169,T1184,T1021
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: linux_logged_users
  observer_can_run: false
  platform: ""
  query: select datetime(time,'unixepoch','UTC') as time_utc,host,user,tty,pid,type
    from logged_in_users;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all create and deleted account - ATT&CK T1136,T1078,T1184,T1021
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: linux_users
  observer_can_run: false
  platform: ""
  query: select * from users;
  team: ""
