# MITRE ATT&CK Technique: linux_home_root_hidden_file_directory
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/linux_home_root_hidden_file_directory.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists hidden direcotry in relevant path - ATT&CK T1158
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: hidden_directories
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%%/.%') OR (fi.path
    like '/root/.%')) AND type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists hidden file in relevant path - ATT&CK T1158,T1100
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: hidden_files
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%%/.%') OR (fi.path
    like '/root/.%')) AND type='regular';
  team: ""
