# MITRE ATT&CK Technique: network_connection_listening
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/network_connection_listening.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the Listening port List - ATT&CK T1043,T1090,T1094,T1205,T1219,T1105,T1065,T1102
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: Snaphost_Windows_Process_Listening_Port
  observer_can_run: false
  platform: windows
  query: select p.name, p.path, lp.port, lp.address, lp.protocol  from listening_ports
    lp LEFT JOIN processes p ON lp.pid = p.pid WHERE lp.port != 0 AND p.name != '';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the network connections from system processes - ATT&CK T1086,T1093,T1020,T1041,T1011,T1029,T1043,T1090,T1094,T1024,T1008,T1219,T1105,T1065
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: Snaphost_Windows_Process_Network_Conn
  observer_can_run: false
  platform: windows
  query: select DISTINCT p.name, p.path, pos.remote_address, pos.remote_port from
    process_open_sockets pos LEFT JOIN processes p ON pos.pid = p.pid WHERE pos.remote_port
    != 0 AND p.name != '';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the Listening port List - ATT&CK T1043,T1090,T1094,T1205,T1219,T1105,T1065,T1102
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: Windows_Process_Listening_Port
  observer_can_run: false
  platform: windows
  query: select p.name, p.path, lp.port, lp.address, lp.protocol  from listening_ports
    lp LEFT JOIN processes p ON lp.pid = p.pid WHERE lp.port != 0 AND p.name != '';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the network connections from system processes - ATT&CK T1086,T1093,T1020,T1041,T1011,T1029,T1043,T1090,T1094,T1024,T1008,T1219,T1105,T1065
  discard_data: false
  interval: 60
  logging: ""
  min_osquery_version: ""
  name: Windows_Process_Network_Conn
  observer_can_run: false
  platform: windows
  query: select DISTINCT p.name, p.path, pos.remote_address, pos.remote_port from
    process_open_sockets pos LEFT JOIN processes p ON pos.pid = p.pid WHERE pos.remote_port
    != 0 AND p.name != '';
  team: ""
