# MITRE ATT&CK Technique: windows_service-persistence
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows_service-persistence.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all installed services configured to start automatically at boot
    - ATT&CK T1050
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: Services
  observer_can_run: false
  platform: ""
  query: SELECT * FROM services WHERE start_type='DEMAND_START' OR start_type='AUTO_START';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Snapshot Services query
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: Snapshot_services
  observer_can_run: false
  platform: ""
  query: SELECT * FROM services;
  team: ""
