# MITRE ATT&CK Technique: windows_new_file_relevant_infection_path
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows_new_file_relevant_infection_path.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under AppData\Local - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: AppData_Local
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\users\%\AppData\Local\%'
    and type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under %TEMP% or AppData\Local\Temp -
    ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1900
  logging: ""
  min_osquery_version: ""
  name: AppData_Local_temp
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\users\%\AppData\Local\temp\%'
    and type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under %APPDATA% or %\AppData\Roaming
    - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1840
  logging: ""
  min_osquery_version: ""
  name: AppData_Roaming
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\users\%\AppData\Roaming\%'
    and type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under ProgramData\Microsoft\Windows\Start
    Menu - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: Programmata_StartMenu
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\ProgramData\Microsoft\Windows\Start
    Menu\%' AND type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under ProgramData\Microsoft\Windows\Start
    Menu\Programs - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: Programmata_StartMenu_program
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\ProgramData\Microsoft\Windows\Start
    Menu\Programs\%' AND type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under Roaming\Microsoft\Windows\Start
    Menu\Programs - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: User_StartMenu_program
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\users\%\AppData\Roaming\Microsoft\Windows\Start
    Menu\Programs\%' AND type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under Roaming\Microsoft\Windows\Start
    Menu\Programs\Startup - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: User_StartMenu_startup
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\users\%\AppData\Roaming\Microsoft\Windows\Start
    Menu\Programs\Startup\%' AND type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under c:\windows - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1800
  logging: ""
  min_osquery_version: ""
  name: windows_new_file
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\Windows\%' and type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious file creation under c:\windows\temp - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1820
  logging: ""
  min_osquery_version: ""
  name: windows_temp
  observer_can_run: false
  platform: windows
  query: SELECT hash.md5, path, file.filename, datetime(file.btime, 'unixepoch', 'UTC')
    as btime, datetime(file.atime, 'unixepoch', 'UTC') as atime, datetime(file.ctime,
    'unixepoch', 'UTC') as ctime, datetime(file.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file USING (path) where path like 'C:\Windows\temp\%' and type='regular';
  team: ""
