# MITRE ATT&CK Technique: windows_new_dir_relevant_infection_path
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows_new_dir_relevant_infection_path.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under AppData\Local - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: AppData_Local_new_directory
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\users\%\AppData\Local\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under %TEMP% or AppData\Local\Temp
    - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1880
  logging: ""
  min_osquery_version: ""
  name: AppData_Local_temp
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\users\%\AppData\local\temp\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under %APPDATA% or %\AppData\Roaming
    - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1840
  logging: ""
  min_osquery_version: ""
  name: AppData_Roaming_new_directory
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\users\%\AppData\Roaming\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under Roaming\Microsoft\Windows\Start
    Menu\Programs - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: User_StartMenu_program
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\users\%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under Roaming\Microsoft\Windows\Start
    Menu\Programs\Startup - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: User_StartMenu_startup
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\users\%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\%' AND
    f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under ProgramData\Microsoft\Windows\Start
    Menu - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: programmata_StartMenu
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\ProgramData\Microsoft\Windows\Start Menu\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under ProgramData\Microsoft\Windows\Start
    Menu\Programs - ATT&CK T1060,T1023
  discard_data: false
  interval: 1860
  logging: ""
  min_osquery_version: ""
  name: programmata_StartMenu_program
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under c:\windows - ATT&CK T1034,T1074,T1044
  discard_data: false
  interval: 1800
  logging: ""
  min_osquery_version: ""
  name: windows_new_directory
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\Windows\%' AND f.type='directory';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check suspicious directory creation under c:\windows\temp - ATT&CK
    T1034,T1074,T1044
  discard_data: false
  interval: 1820
  logging: ""
  min_osquery_version: ""
  name: windows_temp_new_directory
  observer_can_run: false
  platform: windows
  query: select f.path,f.directory,u.username,f.hard_links,f.symlink,datetime(f.btime,
    'unixepoch', 'UTC') as btime, datetime(f.atime, 'unixepoch', 'UTC') as atime,
    datetime(f.ctime, 'unixepoch', 'UTC') as ctime, datetime(f.mtime, 'unixepoch',
    'UTC') as mtime from file f LEFT JOIN users u on f.uid=u.uid where f.path like
    'C:\Windows\temp\%' AND f.type='directory';
  team: ""
