# MITRE ATT&CK Technique: windows-incorrect_path_process
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows-incorrect_path_process.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: conhost.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='conhost.exe' AND LOWER(path)!='c:\windows\system32\conhost.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: crss.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='crss.exe' AND LOWER(path)!='c:\windows\system32\crss.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: dllhost.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='dllhost.exe' AND LOWER(path)!='c:\windows\system32\dllhost.exe'
    AND LOWER(path)!='c:\windows\syswow64\dllhost.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: explorer.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='explorer.exe' AND LOWER(path)!='c:\windows\explorer.exe'
    AND LOWER(path)!='c:\windows\syswow64\explorer.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: lsass.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='lsass.exe' AND LOWER(path)!='c:\windows\system32\lsass.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: services.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='services.exe' AND LOWER(path)!='c:\windows\system32\services.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: smss.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='smss.exe' AND LOWER(path)!='c:\windows\system32\smss.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: svchost.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='svchost.exe' AND LOWER(path)!='c:\windows\system32\svchost.exe'
    AND LOWER(path)!='c:\windows\syswow64\svchost.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: wininit.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='wininit.exe' AND LOWER(path)!='c:\windows\system32\wininit.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: winlogon.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='winlogon.exe' AND LOWER(path)!='c:\windows\system32\winlogon.exe'
    AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK
    T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: wmiprvse.exe_incorrect_path
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE LOWER(name)='wmiprvse.exe' AND LOWER(path)!='c:\windows\system32\wbem\wmiprvse.exe'
    AND LOWER(path)!='c:\windows\syswow64\wbem\wmiprvse.exe' AND path!='';
  team: ""
