# MITRE ATT&CK Technique: windows_process_no_disk_binary
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows_process_no_disk_binary.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect Processes running without a binary on disk
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: Processes_run_without_binary_disk
  observer_can_run: false
  platform: ""
  query: SELECT name, path, pid FROM processes WHERE on_disk = 0;
  team: ""
