# MITRE ATT&CK Technique: windows_scheduled_tasks
# Generated: 2025-07-11 05:18:39 UTC
# Source: https://github.com/teoseller/osquery-attck
# Commit: 6df5f75db20f2b67f6245d1676b97ddd7005aadb
# Usage: fleetctl apply -f by-technique/windows_scheduled_tasks.yml

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all of the tasks in the Windows task scheduler - ATT&CK T1053
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: Scheduled_Task
  observer_can_run: false
  platform: windows
  query: select name,action,path,enabled,datetime(next_run_time,'unixepoch','UTC')
    from scheduled_tasks;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all of the tasks in the Windows task scheduler
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: Snaphost_Scheduled_Task
  observer_can_run: false
  platform: windows
  query: select name,action,path,enabled,datetime(next_run_time,'unixepoch','UTC')
    from scheduled_tasks;
  team: ""
