---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Net Execute, is used in command-line operations for control of users, groups, services, and network connections - ATT&CK T1007
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Network Commands
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%net.exe%';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: SC.exe Execute, Service Control - Create, Start, Stop, Query or Delete any Windows SERVICE. . - ATT&CK T1007
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Service Control
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%sc%';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Tasklist Execute, usaullay used to list task - ATT&CK T1007
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Process Enumeration
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%tasklist%';
  team: ""