apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all of the tasks in the Windows task scheduler - ATT&CK T1053.005 - ATT&CK T1053.005
  discard_data: false
  interval: 3600
  name: MITRE - Scheduled Tasks
  observer_can_run: false
  platform: "windows"
  query: select name,action,path,enabled,datetime(next_run_time,'unixepoch','UTC') from scheduled_tasks;
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all of the tasks in the Windows task scheduler - ATT&CK T1053.005
  discard_data: false
  interval: 28800
  name: MITRE - Scheduled Tasks Monitoring
  observer_can_run: false
  platform: "windows"
  query: select name,action,path,enabled,datetime(next_run_time,'unixepoch','UTC') from scheduled_tasks;
