---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: **AppInit DLLs** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows - ATT&CK T1055.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry AppInit DLLs
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: **AppInit DLLs** Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows - ATT&CK T1055.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Wow6432Node AppInit DLLs
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: **AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows - ATT&CK T1055.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKLM AppInit DLLs
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: **AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows - ATT&CK T1055.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKLM Wow6432Node AppInit DLLs
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""