---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Local system users. - ATT&CK T1082
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Certificates
  observer_can_run: false
  platform: "windows"
  query: select * from certificates;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Users snapshot query - ATT&CK T1082
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Certificates Snapshot
  observer_can_run: false
  platform: "windows"
  query: select * from certificates;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Local system users.
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Programs Snapshot
  observer_can_run: false
  platform: "windows"
  query: select * from programs;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: System information for identification.
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - System Information
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM system_info;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: System info snapshot query
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - System Information Snapshot
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM system_info;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: System uptime
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - System Uptime
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM uptime;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Systeminfo Execute, Systeminfo is a Windows utility that can be used to gather detailed information about a computer. - ATT&CK T1082
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - System Information
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%systeminfo%';
  team: ""