---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Extracted information from Windows crash logs (Minidumps).
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Windows Crashes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM windows_crashes;
  team: ""