---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Taskkill Execute, usaullay used to kill task '
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Process Termination
  observer_can_run: false
  platform: "windows"
  query: select * from file WHERE directory = 'C:\Windows\Prefetch\' and filename like '%taskkill%';
  team: ""