---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run - ATT&CK T1547.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Current User Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1547.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Explorer Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1547.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Local Machine Explorer Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Users Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_USERS\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Windows Startup Items Osquery predefined query - ATT&CK T1547.001
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Startup Items
  observer_can_run: false
  platform: "windows"
  query: select * from startup_items;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1547.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKCU Explorer Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run - ATT&CK T1547.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKCU Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLMU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1547.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKLM Explorer Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Registry Snapshot HKU Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_USERS\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Snapshot Windows Startup Items Osquery predefined query - ATT&CK T1547.001
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Startup Items Snapshot
  observer_can_run: false
  platform: "windows"
  query: select * from startup_items;
  team: ""