---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check mount on the host - ATT&CK T1025,T1052
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Mount Discovery
  observer_can_run: false
  platform: ""
  query: SELECT device, device_alias, flags, path,type from mounts;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: List linux files that are setuid-enabled
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Setuid Binary Discovery
  observer_can_run: false
  platform: ""
  query: select * from suid_bin;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Linux sudoers information - ATT&CK T1169,T1206
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Sudoers Configuration
  observer_can_run: false
  platform: ""
  query: select * from sudoers;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check any bash reverse shell forwarded to the attacker - ATT&CK T1169,T1206
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Sudoers Integrity Check
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where (fi.path like '/etc/sudoers') AND type='regular';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check any bash reverse shell forwarded to the attacker - ATT&CK T1169,T1206
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Reverse Shell Detection
  observer_can_run: false
  platform: ""
  query: SELECT * FROM processes WHERE cmdline LIKE '/bin/bash -i >& /dev/tcp/%';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check USB device on the host - ATT&CK T1052
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - USB Device Discovery
  observer_can_run: false
  platform: ""
  query: SELECT * FROM usb_devices;
  team: ""
