---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIR1 dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Custom Directory Monitoring 1
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIR1/%/%') OR
    (fi.path like '/YOURIMPDIR1/%%/.%') OR (fi.path like '/YOURIMPDIR1/.%') OR (fi.path
    like '/YOURIMPDIR1/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIR2 dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Custom Directory Monitoring 2
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIR2/%/%') OR
    (fi.path like '/YOURIMPDIR2/%%/.%') OR (fi.path like '/YOURIMPDIR2/.%') OR (fi.path
    like '/YOURIMPDIR2/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under YOURIMPDIRn dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Custom Directory Monitoring N
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/YOURIMPDIRn/%/%') OR
    (fi.path like '/YOURIMPDIRn/%%/.%') OR (fi.path like '/YOURIMPDIRn/.%') OR (fi.path
    like '/YOURIMPDIRn/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under all home user dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Home Directory Discovery
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%/%') OR (fi.path
    like '/home/%') OR (fi.path like '/home/%/.%')OR (fi.path like '/home/.%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under root dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Root Directory Discovery
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/root/%/%') OR (fi.path
    like '/root/%') OR (fi.path like '/root/%/.%')OR (fi.path like '/root/.%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under tmp dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Temp Directory Discovery
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/tmp/%/%') OR (fi.path
    like '/tmp/.%')OR (fi.path like '/tmp/%'));
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: 'Lists files and directories under www dir - ATT&CK: T1158,T1100'
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Web Directory Discovery
  observer_can_run: false
  platform: ""
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/var/www/%/%') OR (fi.path
    like '/var/www/%/.%')OR (fi.path like '/var/www/.%') OR (fi.path like '/var/www/.%'));
  team: ""
