---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists last logged in users - ATT&CK T1136,T1078
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists last logged in users
  observer_can_run: false
  platform: "linux"
  query: select datetime(time,'unixepoch','UTC') as time_utc,host,username,tty,pid,type from last;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all logged in users - ATT&CK T1136,T1078,T1169,T1184,T1021
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists all logged in users
  observer_can_run: false
  platform: "linux"
  query: select datetime(time,'unixepoch','UTC') as time_utc,host,user,tty,pid,type from logged_in_users;
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all create and deleted account - ATT&CK T1136,T1078,T1184,T1021
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists all create and deleted account
  observer_can_run: false
  platform: "linux"
  query: select * from users;
  team: ""
