---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: List Local job scheduling with Cron - ATT&CK T1168
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Cron Job Discovery
  observer_can_run: false
  platform: ""
  query: select command, path from crontab;
  team: ""
