---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all chrome extensions - ATT&CK T1176
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists all chrome extensions
  observer_can_run: false
  platform: "linux"
  query: SELECT u.username, ce.* FROM users u CROSS JOIN chrome_extensions ce USING (uid);
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all Firefox addons - ATT&CK T1176
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists all Firefox addons
  observer_can_run: false
  platform: "linux"
  query: SELECT u.username, ce.* FROM users u CROSS JOIN firefox_addons ce USING (uid);
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all Opera extensions - ATT&CK T1176
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Lists all Opera extensions
  observer_can_run: false
  platform: "linux"
  query: SELECT u.username, ce.* FROM users u CROSS JOIN opera_extensions ce USING (uid);
  team: ""
