---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: List shell_history for each users on the system - ATT&CK T1064,T1059,T1153,T1166,T1100,T1055,T1222,T1107,T1146,T1081,T1003,T1033,T1016,T1082,T1069,T1201,T1083,T1217,T1087
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Shell History Analysis
  observer_can_run: false
  platform: ""
  query: select usr.username, sht.command, sht.history_file from shell_history sht
    JOIN users usr ON sht.uid = usr.uid WHERE sht.uid IN (SELECT uid from users);
  team: ""
