---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists all installed services configured to start automatically at boot
    - ATT&CK T1050
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Services
  observer_can_run: false
  platform: ""
  query: SELECT * FROM services WHERE start_type='DEMAND_START' OR start_type='AUTO_START';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Snapshot Services query
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Services Snapshot
  observer_can_run: false
  platform: ""
  query: SELECT * FROM services;
  team: ""
