---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='conhost.exe' AND LOWER(path)!='c:\windows\system32\conhost.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='crss.exe' AND LOWER(path)!='c:\windows\system32\crss.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='dllhost.exe' AND LOWER(path)!='c:\windows\system32\dllhost.exe' AND LOWER(path)!='c:\windows\syswow64\dllhost.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='explorer.exe' AND LOWER(path)!='c:\windows\explorer.exe' AND LOWER(path)!='c:\windows\syswow64\explorer.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='lsass.exe' AND LOWER(path)!='c:\windows\system32\lsass.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='services.exe' AND LOWER(path)!='c:\windows\system32\services.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='smss.exe' AND LOWER(path)!='c:\windows\system32\smss.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='svchost.exe' AND LOWER(path)!='c:\windows\system32\svchost.exe' AND LOWER(path)!='c:\windows\syswow64\svchost.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='wininit.exe' AND LOWER(path)!='c:\windows\system32\wininit.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='winlogon.exe' AND LOWER(path)!='c:\windows\system32\winlogon.exe' AND path!='';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect processes masquerading as legitimate Windows processes - ATT&CK T1034
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Detect processes masquerading as legitimate Windows processes
  observer_can_run: false
  platform: "windows"
  query: SELECT * FROM processes WHERE LOWER(name)='wmiprvse.exe' AND LOWER(path)!='c:\windows\system32\wbem\wmiprvse.exe' AND LOWER(path)!='c:\windows\syswow64\wbem\wmiprvse.exe' AND path!='';
  team: ""
