---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Control Panel_Desktop - ATT&CK T1180
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Control Panel_Desktop
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Control Panel\Desktop';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_WindowsNT_CurrentVersion_winlogon - ATT&CK T1004
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Software_Microsoft_WindowsNT_CurrentVersion_winlogon
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1060
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKEY_CURRENT_USER_Environment - ATT&CK T1037
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKEY_CURRENT_USER_Environment
  observer_can_run: false
  platform: "windows"
  query: select * from registry where key='HKEY_CURRENT_USER\Environment';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run - ATT&CK T1060
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_winlogon - ATT&CK T1004
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_winlogon
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1060
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_Image_File_Execution_Options - ATT&CK T1015
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_Image_File_Execution_Options
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**AppInit DLLs** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows - ATT&CK T1103'
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - **AppInit DLLs** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows
  observer_can_run: false
  platform: windows
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_WindowsNT_CurrentVersion_winlogon - ATT&CK T1004
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_WindowsNT_CurrentVersion_winlogon
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Winlogon';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**AppInit DLLs** Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows - ATT&CK T1103'
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - **AppInit DLLs** Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**Application Shimming** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_custom - ATT&CK T1138'
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - **Application Shimming** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_custom
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\software\microsoft\windows nt\currentversion\appcompatflags\custom';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**Application Shimming** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_installedsdb - ATT&CK T1138'
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - **Application Shimming** Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_installedsdb
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\software\microsoft\windows nt\currentversion\appcompatflags\installedsdb';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Control_Lsa - ATT&CK T1131
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Control_Lsa
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\system\CurrentControlSet\Control\Lsa';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Control_Lsa - ATT&CK T1128,S0108
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Control_Lsa
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Netsh';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Service - ATT&CK T1058
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Service
  observer_can_run: false
  platform: "windows"
  query: select name, type from registry where key='HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_USERS\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1060
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run - ATT&CK T1060
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKCU_Software_Microsoft_Windows_CurrentVersion_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKLMU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run - ATT&CK T1060
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKLMU_Software_Microsoft_Windows_CurrentVersion_Policies_Explorer_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows - ATT&CK T1103'
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - **AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Wow6432Node_Microsoft_Windows NT_CurrentVersion_Windows
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**Application Shimming** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_custom - ATT&CK T1138'
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - **Application Shimming** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_custom
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\software\microsoft\windows nt\currentversion\appcompatflags\custom';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**Application Shimming** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_installedsdb - ATT&CK T1138'
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - **Application Shimming** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_appcompatflags_installedsdb
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\software\microsoft\windows nt\currentversion\appcompatflags\installedsdb';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Snapshot Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Service - ATT&CK T1058
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Snapshot Returns the content of the key HKLM_SYSTEM_CurrentControlSet_Service
  observer_can_run: false
  platform: "windows"
  query: select name, type from registry where key='HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: '**AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows - ATT&CK T1103'
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - **AppInit DLLs** Snapshot Returns the content of the key HKLM_Software_Microsoft_WindowsNT_CurrentVersion_Windows
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows' and name='AppInit_DLLs';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Returns the content of the key HKU_Software_Microsoft_Windows_CurrentVersion_Run
  observer_can_run: false
  platform: "windows"
  query: select name,type,data from registry where key='HKEY_USERS\Software\Microsoft\Windows\CurrentVersion\Run';
  team: ""
