---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Snapshot List Windows System running processes - ATT&CK T1034,T1121,T1117,T1085
  discard_data: false
  interval: 28800
  logging: ""
  min_osquery_version: ""
  name: MITRE - Snapshot List Windows System running processes
  observer_can_run: false
  platform: "windows"
  query: select processes.pid, processes.name, users.username, processes.path from processes LEFT JOIN users ON processes.uid = users.uid WHERE processes.path != '';
  team: ""
---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: List Windows System running processes. - ATT&CK T1034,T1121,T1117,T1085
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - List Windows System running processes.
  observer_can_run: false
  platform: "windows"
  query: select processes.pid, processes.name, users.username, processes.path, processes.cmdline from processes LEFT JOIN users ON processes.uid = users.uid WHERE processes.path != '';
  team: ""
