---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists files and directories under all home user dir - ATT&CK T1083 File and Directory Discovery
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Home Directory Discovery
  observer_can_run: false
  platform: "linux"
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%/%') OR (fi.path
    like '/home/%') OR (fi.path like '/home/%/.%')OR (fi.path like '/home/.%'));
  team: ""

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists files and directories under www dir - ATT&CK T1083 File and Directory Discovery
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Web Directory Discovery
  observer_can_run: false
  platform: "linux"
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/var/www/%/%') OR (fi.path
    like '/var/www/%/.%')OR (fi.path like '/var/www/.%') OR (fi.path like '/var/www/.%'));
  team: ""

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Detect loading, unloading, and manipulating modules on Linux systems - ATT&CK T1547.006 Kernel Modules and Extensions
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Kernel Module Activity
  observer_can_run: false
  platform: "linux"
  query: select usr.username, sht.command, sht.history_file from shell_history sht
    JOIN users usr ON sht.uid = usr.uid WHERE sht.uid IN (SELECT uid from users) AND
    (sht.command LIKE '%modprobe%' OR sht.command LIKE '%insmod%' OR sht.command  LIKE
    '%lsmod%' OR sht.command  LIKE '%rmmod%' OR sht.command LIKE '%modinfo%'
    OR sht.command LIKE '%linux-headers-$%'OR sht.command LIKE '%kernel-devel-$%');
  team: ""

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists hidden directory in relevant path - ATT&CK T1564.001 Hidden Files and Directories
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Hidden Directory Discovery
  observer_can_run: false
  platform: "linux"
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%%/.%') OR (fi.path
    like '/root/.%')) AND type='directory';
  team: ""

---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Lists hidden file in relevant path - ATT&CK T1564.001 Hidden Files and Directories
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Hidden File Discovery
  observer_can_run: false
  platform: "linux"
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC')
    as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime,
    'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime
    FROM hash JOIN file fi USING (path) where ((fi.path like '/home/%%/.%') OR (fi.path
    like '/root/.%')) AND type='regular';
  team: ""