---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check mount on the host - ATT&CK T1025,T1052
  discard_data: false
  interval: 600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Mount Discovery
  observer_can_run: false
  platform: "linux,darwin"
  query: SELECT device, device_alias, flags, path, type from mounts;
  team: ""