---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Check any bash reverse shell forwarded to the attacker - ATT&CK T1169,T1206
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Sudoers Integrity Check
  observer_can_run: false
  platform: "linux,darwin"
  query: SELECT hash.sha1, fi.path, fi.filename, datetime(fi.btime, 'unixepoch', 'UTC') as btime, datetime(fi.atime, 'unixepoch', 'UTC') as atime, datetime(fi.ctime, 'unixepoch', 'UTC') as ctime, datetime(fi.mtime, 'unixepoch', 'UTC') as mtime FROM hash JOIN file fi USING (path) where (fi.path like '/etc/sudoers') AND type='regular';
  team: ""