---
apiVersion: v1
kind: query
spec:
  automations_enabled: false
  description: Linux sudoers information - ATT&CK T1169,T1206
  discard_data: false
  interval: 3600
  logging: ""
  min_osquery_version: ""
  name: MITRE - Sudoers Configuration
  observer_can_run: false
  platform: "linux,darwin"
  query: select * from sudoers;
  team: ""